name: CI

on:
  push:
    branches: [ main, '0.2-dev', '**' ]
  pull_request:
    branches: [ main, '0.2-dev' ]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -- -D warnings
      - name: build
        run: cargo build --verbose
